<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>307d2d07-11e1-4505-b46c-c1376efbe342</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\StashLock.Server\StashLock.Server.csproj" />
  </ItemGroup>

</Project>
